### ISSUE TITLE
boden open doesn't work on Fedora

### ISSUE THREAD

**Issue by ShadowMitia** [AshampooSystems/boden#10]
I followed the instructions to setup boden on Fedora.

I get an error when I try to open the demo project :

> [2019-07-13 12:05:48,320] Defaulting to: android - AndroidStudio
> [2019-07-13 12:05:48,320] Build system does not match the one used when the projects for this platform were first prepared. Cleaning existing build files.
> [2019-07-13 12:05:48,335] Preparing /data/dimitri/gits/boden/build/android/std/AndroidStudio
> [2019-07-13 12:05:48,335] Preparing android environment...
> [2019-07-13 12:05:48,335] Ensuring that all necessary android packages are installed...
> Warning: File /home/dimitri/.android/repositories.cfg could not be loaded.
> Warning: File /home/dimitri/.android/repositories.cfg could not be loaded.      
> [=======================================] 100% Computing updates...             
> [2019-07-13 12:05:52,158] Done updating packages.
> No Gradle daemons are running.
> [2019-07-13 12:05:52,808] Configuring ...
> -- Check for working C compiler: /home/dimitri/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
> -- Check for working C compiler: /home/dimitri/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/dimitri/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
> -- Check for working CXX compiler: /home/dimitri/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Boden platform:
> --   Name: android
> --   Family: posix
> -- Boden configuration:
> --   Uses foundation kit: No
> --   Uses java: Yes
> --   Force shared: Yes
> --   Force static: No
> -- clang-format was not found!
> -- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
> -- Using the single-header code from /home/dimitri/gits/boden/3rdparty/json/single_include/
> -- CMake Warning (dev) at 3rdparty/googletest/CMakeLists.txt:3 (project):
>   Policy CMP0048 is not set: project() command manages VERSION variables.
>   Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   The following variable(s) would be set to empty:
> 
>     PROJECT_VERSION
>     PROJECT_VERSION_MAJOR
>     PROJECT_VERSION_MINOR
>     PROJECT_VERSION_PATCH
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - found
> -- Found Threads: TRUE  
> -- Boden library configuration:
> --   Shared: Off
> --   Architecture: 32 bit
> -- Package name: boden-0.2.0-android-x86-28-%BUILD_TYPE%-Clang
> -- Configuring done
> [2019-07-13 12:05:54,270] Done.
> [2019-07-13 12:05:54,270] Generating ...
> -- Generating done
> Traceback (most recent call last):
>   File "/data/dimitri/gits/boden/./bauer/bauer.py", line 66, in main
>     return run(argv)
>   File "/data/dimitri/gits/boden/./bauer/bauer.py", line 62, in run
>     commandProcessor.process()
>   File "/data/dimitri/gits/boden/./bauer/commandprocessor.py", line 119, in process
>     self.prepare(configuration, platformState)
>   File "/data/dimitri/gits/boden/./bauer/commandprocessor.py", line 133, in prepare
>     self.androidExecutor.prepare(platformState, configuration, self.args)
>   File "/data/dimitri/gits/boden/./bauer/androidexecutor.py", line 84, in prepare
>     self.prepareAndroidStudio(platformState, configuration, androidAbi, androidHome, buildDir, args)
>   File "/data/dimitri/gits/boden/./bauer/androidexecutor.py", line 168, in prepareAndroidStudio
>     project = config["main-project"]
> KeyError: 'main-project'

I tried both `./boden` and `python boden`

Do I have a dependency missing ?

I'm using Fedora 30.

**Comment by Maddimax** [comment]
This can sometime happen when there are issues with upper/lower case in a directory path. Is the case correct in this path: /data/dimitri/gits/boden/ ?

Can you run `./boden ..` with "-d" added, that will give some more debug output and create a file called "codemodel.debug.json" in the boden folder which might help me understand what the issue is.

**Comment by ShadowMitia** [comment]
Thank you for your answer!

The path is correct but it's a symlinked path. This is what was causing the issue.
I was running from /home/dimitri/gits/boden, when the "real" path is "/data/dimitri/gits/boden".

I guess the script got confused over the path. 

If I clone and run the script outside of the symlink path it runs fine.

I can still send you the debug information if you need it.

**Comment by Maddimax** [comment]
Thats great, I'll put an issue into our backlog to fix that. I won't need the debug info.

Thanks for your help!

**Comment by ShadowMitia** [comment]
Thank you, looking forward to try this out!
