### ISSUE TITLE
Bodendemo seems to be broken on Android

### ISSUE THREAD

**Issue by lingnand** [AshampooSystems/boden#8]
Just tried the build - it worked and I managed to run the app on my phone. But when I tried out some menu items in the list and clicked back button to go back to the menu page I got this:

![Screenshot_20190628-235449](https://user-images.githubusercontent.com/1991754/60375369-d5d9a980-9a00-11e9-8783-a1a522247ed8.png)

It seems that each item is still clickable and functional in that sense; it's just that all the labels are gone.

**Comment by Maddimax** [comment]
Thanks for your report.

I cannot reproduce the issue at the moment with either the Simulator or a Samsung Galaxy 9 ( running Android API 28 ).

Can you provide the following information:
* Model of device
* Android Version (API Version and whether its vanilla or something custom ) on the device
* Does this happen after the first selection / back, or do you have to click through a few of the demos first, maybe even after a specific demo page

**Comment by lingnand** [comment]
> Model of device

Blackberry Key 2

> Android Version, API Version and whether its vanilla or something custom, on the device

Android 8.1.0; mostly vanilla (manufacturer only added some apps of their own)

> Does this happen after the first selection / back, or do you have to click through a few of the demos first, maybe even after a specific demo page

It happens consistently after the first selection / back, regardless which item I click.

I'm compiling the demo using API 28 as specified in the bauer scripts.

**Comment by Maddimax** [comment]
Thanks, I can reproduce the issue with Android 8.1 as well.

I'll try to get a fix out as soon as possible.

**Comment by Maddimax** [comment]
We've investigated the issue and it turns out it is a specific problem with Android 8.1. Android 8.0 does not exhibit the issue. We've added it to our backlog as the issue is too complex for a quick fix.

As a workaround, setting the backgroundColor of the View solves the issue as well.

**Comment by lingnand** [comment]
Ok, thanks for the quick turnaround.

**Comment by Maddimax** [comment]
We've solved the issue now by moving from a ListView based implementation to a RecyclerView based one.
